//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealWorldApp.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealWorldApp.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בהרשמה  אני מסכים\ה לתנאי השימוש ו-הפרטיות.
        /// </summary>
        internal static string Accept_Terms {
            get {
                return ResourceManager.GetString("Accept Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספה לעגלה.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חיוג.
        /// </summary>
        internal static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עגלה.
        /// </summary>
        internal static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיקה.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אישור סיסמא.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צרו קשר.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצירת חשבון חדש.
        /// </summary>
        internal static string Create_New_Account {
            get {
                return ResourceManager.GetString("Create New Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אימייל.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיימתי לבחור (:.
        /// </summary>
        internal static string FinishSelecting {
            get {
                return ResourceManager.GetString("FinishSelecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירת דג.
        /// </summary>
        internal static string FishSelect {
            get {
                return ResourceManager.GetString("FishSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון ליצירת קשר.
        /// </summary>
        internal static string ForFurtherSupport {
            get {
                return ResourceManager.GetString("ForFurtherSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם מלא.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לך כבר חשבון?.
        /// </summary>
        internal static string HaveAnAccount {
            get {
                return ResourceManager.GetString("HaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלום.
        /// </summary>
        internal static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היי .
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחברות.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בוצעה ב.
        /// </summary>
        internal static string MadeOn {
            get {
                return ResourceManager.GetString("MadeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אולי אח&quot;כ.
        /// </summary>
        internal static string MaybeLater {
            get {
                return ResourceManager.GetString("MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירת בשר.
        /// </summary>
        internal static string MeatSelect {
            get {
                return ResourceManager.GetString("MeatSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ההזמנות שלי.
        /// </summary>
        internal static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פירוט הזמנה.
        /// </summary>
        internal static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הזמנה מס.
        /// </summary>
        internal static string OrderNum {
            get {
                return ResourceManager.GetString("OrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היסטוריית הזמנות.
        /// </summary>
        internal static string OrdersHistory {
            get {
                return ResourceManager.GetString("OrdersHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התפריט שלנו.
        /// </summary>
        internal static string OurMenu {
            get {
                return ResourceManager.GetString("OurMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוספות בתשלום.
        /// </summary>
        internal static string PaidSideDishes {
            get {
                return ResourceManager.GetString("PaidSideDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמא.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביצוע הזמנה.
        /// </summary>
        internal static string PlaceMyOrder {
            get {
                return ResourceManager.GetString("PlaceMyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הזמנה.
        /// </summary>
        internal static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצרים פופולריים.
        /// </summary>
        internal static string PopularProducts {
            get {
                return ResourceManager.GetString("PopularProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הבא.
        /// </summary>
        internal static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיאור מוצר.
        /// </summary>
        internal static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי המזמין.
        /// </summary>
        internal static string ProvideDetails {
            get {
                return ResourceManager.GetString("ProvideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כמות.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרשמה.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סהכ.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר ליחידה.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירת ירק.
        /// </summary>
        internal static string VegSelect {
            get {
                return ResourceManager.GetString("VegSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברוכים הבאים .
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העגלה שלך.
        /// </summary>
        internal static string YourCart {
            get {
                return ResourceManager.GetString("YourCart", resourceCulture);
            }
        }
    }
}
